//                              -*- Mode: C++ -*- 
// RnamlWriter.h
// Copyright © 2003-05 Laboratoire de Biologie Informatique et Théorique
//                  Université de Montréal.
// Author           : Martin Larose
// Created On       : Thu Jul 10 14:43:57 2003
// $Revision: 1.6 $
// $Id: RnamlWriter.h,v 1.6 2005-04-12 20:14:18 larosem Exp $
// 
// This file is part of mccore.
// 
// mccore is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// mccore is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with mccore; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


#ifndef _mccore_RnamlWriter_h_
#define _mccore_RnamlWriter_h_

#include <vector>

namespace rnaml
{
  class Atom;
  class Base;
  class BaseId;
  class Model;
  class ModelId;
  class Molecule;
  class MoleculeId;
  class PrintStream;
  class Rnaml;
  class Segment;
  class SeqAnnotation;
  class Sequence;
  class StrAnnotation;
}

using namespace std;



namespace mccore
{
  class Atom;
  class AbstractModel;
  class GraphModel;
  class Molecule;
  class ResId;
  class Residue;
  
  
  
  /**
   * @short Writer for mccore objects to rnaml.
   *
   * This class writes the mccore objects into a stream.  The objects are
   * transformed into rnamlObjects, then outputted to the stream.
   *
   * @author Martin Larose (<a href="larosem@iro.umontreal.ca">larosem@iro.umontreal.ca</a>).
   */
  class RnamlWriter
  {
    /**
     * The print stream.
     */
    rnaml::PrintStream *ps;
    
  public:
    
    // LIFECYCLE ------------------------------------------------------------
    
    /**
     * Initializes the writer with a file name.
     * @param name the file name.
     * @param zipped whether the ouput file must be zipped; default false.
     */
    RnamlWriter (const char *name, bool zipped = false);
    
    /**
     * Initializes the object.
     * @param ps the print stream.
     */
    RnamlWriter (rnaml::PrintStream *ps) : ps (ps) { }
    
    /**
     * Destroys the object.
     */
    virtual ~RnamlWriter ();
    
    // OPERATORS ------------------------------------------------------------
    
    // ACCESS ---------------------------------------------------------------
    
    // METHODS --------------------------------------------------------------
    
    /**
     * Transforms a mccore Atom to a rnaml Atom.
     * @param atom the mccore Atom.
     * @return the rnaml Atom.
     */
    static rnaml::Atom* toRnaml (const mccore::Atom &atom);

    /**
     * Transforms a mccore ResId to a rnaml BaseId.
     * @param molId optional MoleculeId, 0 when not used.
     * @param mId optional ModelId, 0 when not used.
     * @param id the ResId.
     * @return the rnaml BaseId.
     */
    static rnaml::BaseId* toBaseId (rnaml::MoleculeId *molId, rnaml::ModelId *mId, const ResId &id);
    
    /**
     * Transforms a mccore Residue to a rnaml Base.
     * @param residue the mccore Residue.
     * @return the rnaml Base.
     */
    static rnaml::Base* toRnaml (const Residue &residue);

    /**
     * Builds the structure annotation elements for an annotated GraphModel.
     * @param model the annotated GraphModel.
     * @return the rnaml structure annotation StrAnnotation.
     */
    static rnaml::StrAnnotation* strAnnotate (const GraphModel &model);
    
    /**
     * Transforms a mccore AbstractModel to a rnaml Model.
     * @param model the mccore AbstractModel.
     * @return the rnaml Model.
     */
    static rnaml::Model* toRnaml (const AbstractModel &model);

  private:
    
    /**
     * Builds the set of adjacent sequences in sequences from the given
     * annotated model.  Sequences are separated when changes in chain id
     * occurs or when gaps in number ids.  No sequence information are given
     * for lone residues.
     * @param m the rnaml Molecule.
     * @param model the annotated model.
     */
    static void buildStrands (vector< vector< const Residue *> > &sequences, const GraphModel &model);

    /**
     * Builds the rnaml sequence element from a collection of residues as
     * generated by buildStrands.
     * @param seq a collection of adjacent residues from 5' to 3'.
     * @return the rnaml sequence element.
     */
    static rnaml::Sequence* toSequence (const vector< const Residue* > &seq);

    /**
     * Builds the rnaml seq-annotation element from a collection of residues
     * as generated by buildStrands.
     * @param seq a collection of adjacent residues from 5' to 3'.
     * @return the rnaml seq-annotation element.
     */
    static rnaml::SeqAnnotation* toSeqAnnotation (const vector< const Residue* > &seq);

    /**
     * Builds the rnaml segment element from a collection of residues as
     * generated by buildStrands.
     * @param seq a collection of adjacent residues from 5' to 3'.
     * @return the rnaml segment element.
     */
    static rnaml::Segment* toSegment (const vector< const Residue* > &seq);
    
  public:
    
    /**
     * Close the stream. Once a stream has been closed, further write ()
     * invocations will do nothing. Closing a previously-closed stream,
     * however, has no effect.
     */
    void close ();
    
    // I/O  -----------------------------------------------------------------
    
    /**
     * Writes the molecule wrapped in a rnaml document.
     * @param molecule the Molecule to write.
     */
    void write (const Molecule &molecule);
    
  };
}

#endif
